### PR TITLE
svg gusset documentation

### PR DESCRIPTION
**Pull request by jurra**
@polemidis, is this a proper way of doing the svgs, or just the shape of the gusset?
With shape or also "techdraw" template, I think should be just the shape of the gusset. Still finding how it should be.

### CODE REVIEW

**Comment by polemidis** [comment]
I believe they are not ok. It looks like they are not in scale.How did you made them? I am pretty sure that the correct way is to select the object, move it to X/Y plane and do a File/Export and for the file type choose the "Flattened svg", or the "Drawing"

**Comment by jurra** [comment]
I am going to check. But I think they are ok. I checked the scale and
dimensions.

**Comment by polemidis** [comment]
ok. Maybe I am wrong. I will double check later when I get to my computer. I just had the air drier exploded, PVC didn't stand the pressure. My bad. With the svg's I can start cutting. Did you see the file tree on the google drive? I have to make some coding on which files are for plasma cut, which are just purchased, so it will make the process easier.

**Comment by jurra** [comment]
Thasts bad man. Air drier exploded :(

**Comment by jurra** [comment]
Yes i saw the file tree. I think it could also go on the wiki.

**Pull request merged**
